// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9_gpT7j1lO9oRLsxKbRob4Nq1pXk9R6g',
    appId: '1:7309717003:web:a35d7ef74302a8ae97210e',
    messagingSenderId: '7309717003',
    projectId: 'imc-backend-tran',
    authDomain: 'imc-backend-tran.firebaseapp.com',
    storageBucket: 'imc-backend-tran.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHEQ-aVPTpv5jdNU7VaCXW6lkyOb2Alhw',
    appId: '1:7309717003:android:81ad667a29a8757f97210e',
    messagingSenderId: '7309717003',
    projectId: 'imc-backend-tran',
    storageBucket: 'imc-backend-tran.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxKZ7vlgI__65d8Ym7zFmGOhgjL_EAfuU',
    appId: '1:7309717003:ios:8b404e475705a18d97210e',
    messagingSenderId: '7309717003',
    projectId: 'imc-backend-tran',
    storageBucket: 'imc-backend-tran.firebasestorage.app',
    iosBundleId: 'com.example.imcSecured',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxKZ7vlgI__65d8Ym7zFmGOhgjL_EAfuU',
    appId: '1:7309717003:ios:8b404e475705a18d97210e',
    messagingSenderId: '7309717003',
    projectId: 'imc-backend-tran',
    storageBucket: 'imc-backend-tran.firebasestorage.app',
    iosBundleId: 'com.example.imcSecured',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9_gpT7j1lO9oRLsxKbRob4Nq1pXk9R6g',
    appId: '1:7309717003:web:2f13e0328e2d5ae397210e',
    messagingSenderId: '7309717003',
    projectId: 'imc-backend-tran',
    authDomain: 'imc-backend-tran.firebaseapp.com',
    storageBucket: 'imc-backend-tran.firebasestorage.app',
  );
}
